version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  pokedex_scraper:
    level: DEBUG
    handlers:
      - console
    propagate: false
  scrapy:
    level: INFO
    handlers:
      - console
    propagate: false
  asyncio:
    level: INFO
    handlers:
      - console
    propagate: false
root:
  level: DEBUG
  handlers:
    - console